### ISSUE TITLE
Rails 5 release

### ISSUE THREAD

**Issue by luislezcair** [ywjno/bootstrap-timepicker-rails-addon#4]
Hi. I'm on the process of upgrading an app to Rails 5 where I'm using this gem and I saw that PR #3 makes the necessary changes to support Rails 5.

Would it be possible to do an official release to rubygems.org? I know I can simply point my Gemfile to this repo, but since is just a small change it would be great to update without doing so.

Thanks!

**Comment by ywjno** [comment]
Hello. I just upgrade new version in rubygems.com, and thanks your issue.

**Comment by luislezcair** [comment]
Great! Thanks!
